### ISSUE TITLE
rectangular conformalmap

### ISSUE THREAD

**Issue by Mxp990329** [IngInx747/hyperbolic-ricci-flow#1]
Hello, do you have a Ricciflow conformal mapping method for Genus-0？ Thank you for seeing this comment.

**Comment by IngInx747** [comment]
Based on your title and context, I suppose you meant topological disk by Genus-0, instead of sphere whose genus is also 0. There are ways to conformally map a 3D disk to a polygon shape in 2D, per your choice. RC flow is a preprocessing step to any of them and is optional most of time
